 services:
   database:
     image: postgres:alpine
     env_file:
       - .env
     environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
     volumes:
       - postgres_dat:/var/lib/postgresql/data
      # - ./sql/migrations/
     healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
