[project]
name = "drugrepurpose-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chembl-webresource-client>=0.10.9",
    "fastapi[standard]>=0.128.0",
    "lxml>=6.0.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "requests>=2.32.5",
]
